import { Header } from '@/components/shared';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function HomeLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <main className="min-h-screen">
            <Header />
            {children}
            {modal}
        </main>
    );
}